name: worldjam_new_fixed
description: Application musicale WorldJam (version stable)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Services en ligne ---
  supabase_flutter: ^2.10.3
  gotrue: ^2.16.0
  realtime_client: ^2.6.0

  # --- Audio ---
  audioplayers: ^6.5.1
  record: ^6.1.2

  # --- Fichiers ---
  file_picker: ^8.1.2

  # --- Utilitaires ---
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  mime: ^2.0.0
  uuid: ^4.5.1
  rxdart: ^0.28.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
